project_id = "tbfeefkmqpzdzubazums"

[functions.risk-explain]
verify_jwt = false

[functions.stock-data]
verify_jwt = false

[functions.stock-buzz]
verify_jwt = false

[functions.watchlist-summary]
verify_jwt = false

[functions.stock-tweets]
verify_jwt = false

[functions.stock-screener]
verify_jwt = false

[functions.validate-nova-token]
verify_jwt = false

[functions.referral-proxy]
verify_jwt = false
